### ISSUE TITLE
Key Prop in React component

### ISSUE THREAD

**Issue by Nirdosh1024** [rushik1992/react-hierarchy-chart#2]
### Expected Behavior: 
I used the code provided in the examples and the documentation, The chart should have been visible on the screen with no warnings.

### Actual Behavior: 
The chart was visible on the screen but there was this warning in the console box : `Each child in a list should have a unique "key" prop.
Check the render method of "ReactHierarchy" ` as well as `Check the render method of "HierarchyNode".`

### Environment: 
I am using react with vite configuration without typescript only jsx. I tried passing the key prop to the div inside the `randerNode` method but It didn't worked. 

I am new to writing issues on github, so kindly ignore if there is any mistake in raising an issue.

**Comment by mestre-hugo** [comment]
I proposed a fix in this [pull request](https://github.com/rushik1992/react-hierarchy-chart/pull/3)

**Comment by Nirdosh1024** [comment]
Thank you for the help man, I really appreciate that.
